### ISSUE TITLE
客户端要知道任务是否完成必须要进行轮循的方式去查去知道吗

### ISSUE THREAD

**Issue by xj13568542105** [mixbasic/delayer-client-golang#1]
客户端要知道任务是否完成必须要进行轮循的方式去查去知道吗，能不能在服务端配置一个任务触发完成时做一个地址回调处理，这样客户端方便处理逻辑

**Comment by onanying** [comment]
客户端获取到的信息都是到期要执行的信息，执行逻辑是用户自己实现，客户端只是取出到期的信息，没到期的取不到

**Comment by xj13568542105** [comment]
假设我有一个自动关闭的订单,通过客户端发送到服务端，然后到时立马执行关闭，这时应该怎么处理呢，服务端只是存储了要执行的信息,但是客户端在未触发的情况并不知道他是否是到达了指定时间，是否需要执行订单关闭

**Comment by onanying** [comment]
当你用 client push 一个任务，设定的时间是 3600s 后，这时你用另一个进程或协程，使用 client pop 数据，当时是 pop 不到这个数据的，只有在 3600s 后才能 pop 到，pop 到数据了就说明这个任务到了执行时间，这个时候就要执行任务了。
